server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.175.66
  rabbitmq:
    host: 192.168.175.66
    virtual-host: /chau
    username: Chau
    password: 123123

gmall:
  jwt:
    pubKeyPath: D:\\workspace-idea\\gmall\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN # cookie的名称

alipay:
  app_id: 2016101500691640
  notify_url: http://zv8o0q5skm.52http.net/api/order/pay/success # 域名是哲西云提供的域名，路径是订单支付成功回调的路径
  return_url: http://localhost:2000/pay/success.html
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do